"""Generate the native tokenizer's Unicode tables from the running interpreter.

build.rs runs this with the interpreter the extension is built for (PYO3_PYTHON, set by
maturin), so raggio_native folds and splits text exactly as that interpreter's
raggio.store._fold_tokens does: str.lower() (Final_Sigma included), NFKD, drop the
combining marks, split on the [^\\W_] class. Stdlib only.

Usage: python gen_unicode.py OUT.rs
"""

import re
import sys
import unicodedata

WORD_RE = re.compile(r"[^\W_]")  # the character class of raggio.store._TOKEN_RE
SIGMA = 0x3A3  # the only code point whose str.lower() depends on its context


def fold(s: str) -> str:
    """raggio.store._fold, restated so the build does not import raggio."""
    return "".join(c for c in unicodedata.normalize("NFKD", s.lower()) if not unicodedata.combining(c))


def ranges(cps: list[int]) -> list[tuple[int, int]]:
    out: list[list[int]] = []
    for cp in cps:
        if out and out[-1][1] == cp - 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return [(a, b) for a, b in out]


def tables() -> dict:
    word, ci, cased, fold_keys, fold_vals = [], [], [], [], []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue  # lone surrogates never reach the extension (UTF-8 extraction rejects them)
        c = chr(cp)
        if WORD_RE.match(c):
            word.append(cp)
        # CPython's Final_Sigma rule (unicodeobject.c, handle_capital_sigma) reads its
        # Case_Ignorable and Cased tables, which Python does not expose. Probe them:
        #   c + SIGMA       lowers to final sigma iff c is cased and not case-ignorable
        #   "A" + c + SIGMA lowers to final sigma iff c is case-ignorable or cased
        alone = (c + "Σ").lower()[-1] == "ς"
        after_a = ("A" + c + "Σ").lower()[-1] == "ς"
        if after_a and not alone:
            ci.append(cp)
        elif alone:
            cased.append(cp)
        if cp != SIGMA:
            f = fold(c)
            if f != c:
                fold_keys.append(cp)
                fold_vals.append(f)
    return {"word": ranges(word), "ci": ranges(ci), "cased": ranges(cased),
            "fold_keys": fold_keys, "fold_vals": fold_vals}


def render(t: dict) -> str:
    def rs_ranges(name: str, rs: list[tuple[int, int]]) -> str:
        body = ",".join(f"(0x{a:X},0x{b:X})" for a, b in rs)
        return f"pub static {name}: &[(u32, u32)] = &[{body}];\n"

    offs, flat = [0], []
    for f in t["fold_vals"]:
        flat.extend(f)
        offs.append(len(flat))
    return "".join([
        f"// generated by gen_unicode.py from Python {sys.version.split()[0]}; do not edit\n",
        f'pub const UNIDATA_VERSION: &str = "{unicodedata.unidata_version}";\n',
        rs_ranges("WORD", t["word"]),
        rs_ranges("CASE_IGNORABLE", t["ci"]),
        rs_ranges("CASED", t["cased"]),
        "pub static FOLD_KEYS: &[u32] = &[" + ",".join(f"0x{k:X}" for k in t["fold_keys"]) + "];\n",
        "pub static FOLD_OFFS: &[u32] = &[" + ",".join(map(str, offs)) + "];\n",
        "pub static FOLD_CHARS: &[char] = &[" + ",".join(f"'\\u{{{ord(ch):X}}}'" for ch in flat) + "];\n",
    ])


if __name__ == "__main__":
    with open(sys.argv[1], "w", encoding="utf-8", newline="\n") as out:
        out.write(render(tables()))
